Repository kuberMAPtes/noon-main-api-server, pull requests merged in 2024-06, with the labels that each got.

#12 Winterhana/#3/private test
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  src/main/java/com/kube/noon/feed/service/FeedService.java
Labels: chore

#13 feat: 네이버 지도 기반 Geocoding, Reverse Geocoding API 데이터 가져오기 구현
  pom.xml
  src/main/java/com/kube/noon/places/domain/Place.java
  src/main/java/com/kube/noon/places/exception/PlaceNotFoundException.java
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepository.java
  src/main/java/com/kube/noon/places/repository/PlacesRepository.java
  src/test/java/com/kube/noon/places/repository/TestPlacesNaverMapsApiRepository.java
Labels: feat

#18 chore: 공통으로 쓰이는 객체하고 환경설정 정의
  src/main/java/com/kube/noon/common/PublicRange.java
  src/main/resources/application.properties
  src/main/resources/mybatis-mapper/SampleMapper.xml
  src/test/java/com/kube/noon/common/TestPublicRange.java
Labels: chore

#16 feat: 장소 검색 비즈니스 로직 구현
  src/main/java/com/kube/noon/places/domain/Place.java
  src/main/java/com/kube/noon/places/domain/Position.java
  src/main/java/com/kube/noon/places/domain/PositionRange.java
  src/main/java/com/kube/noon/places/dto/PlaceDto.java
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepository.java
  src/main/java/com/kube/noon/places/repository/PlacesRepository.java
  src/main/java/com/kube/noon/places/service/PlacesService.java
  src/main/java/com/kube/noon/places/service/PlacesServiceImpl.java
  src/test/java/com/kube/noon/places/repository/TestPlacesNaverMapsApiRepository.java
  src/test/java/com/kube/noon/places/service/TestPlacesServiceImpl.java
Labels: feat

#21 chore: JPA 관련 설정 추가
  src/main/resources/application.properties
Labels: chore

#25 Yejiheo/#5/building profile repository
  pom.xml
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/domain/Building.java
  src/main/java/com/kube/noon/building/domain/BuildingSubscription.java
  src/main/java/com/kube/noon/building/dto/BuildingDto.java
  src/main/java/com/kube/noon/building/dto/BuildingZzimDto.java
  src/main/java/com/kube/noon/building/repository/BuildingProfileRepository.java
  src/main/java/com/kube/noon/building/repository/mapper/BuildingProfileMapper.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/common/zzim/Zzim.java
  src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
  src/main/java/com/kube/noon/common/zzim/ZzimType.java
  src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
  src/main/java/com/kube/noon/customersupport/domain/Chatbot.java
  src/main/java/com/kube/noon/customersupport/domain/ChatbotConversation.java
  src/main/java/com/kube/noon/customersupport/domain/Notice.java
  src/main/java/com/kube/noon/customersupport/domain/Report.java
  src/main/resources/mybatis-mapper/buildingProfile/BuildingProfileMapper.xml
  src/test/java/com/kube/noon/building/repository/TestBuildingProfileRepository.java
  src/test/java/com/kube/noon/building/service/TestBuildingService.java
  src/test/java/com/kube/noon/customersupport/Service/TestCustomerSupportService.java
Labels: feat

#30 Winterhana/#15/feed basic logic
  src/main/java/com/kube/noon/common/FeedCategory.java
  src/main/java/com/kube/noon/common/FileType.java
  src/main/java/com/kube/noon/feed/domain/Feed.java
  src/main/java/com/kube/noon/feed/domain/FeedAttachement.java
  src/main/java/com/kube/noon/feed/domain/FeedAttachment.java
  src/main/java/com/kube/noon/feed/domain/FeedComment.java
  src/main/java/com/kube/noon/feed/domain/Tag.java
  src/main/java/com/kube/noon/feed/domain/TagFeed.java
  src/main/java/com/kube/noon/feed/dto/FeedAttachmentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedCommentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/TagDto.java
  src/main/java/com/kube/noon/feed/dto/TagFeedDto.java
  src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedCommentRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagFeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/resources/mybatis-mapper/TagMapper.xml
  src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedCommentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
Labels: feat

#23 feat: NotificationRepository 구현
  src/main/java/com/kube/noon/notification/converter/NotificationTypeConverter.java
  src/main/java/com/kube/noon/notification/domain/Notification.java
  src/main/java/com/kube/noon/notification/domain/NotificationType.java
  src/main/java/com/kube/noon/notification/dto/NotificationDto.java
  src/main/java/com/kube/noon/notification/repository/NotificationRepository.java
  src/main/java/com/kube/noon/notification/service/NotificationService.java
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
  src/main/java/com/kube/noon/places/repository/PlacesRepository.java
  src/main/java/com/kube/noon/places/service/PlacesService.java
  src/test/java/com/kube/noon/notification/repository/TestNotificationRepository.java
  src/test/java/com/kube/noon/places/repository/TestPlacesNaverMapsApiRepositoryImpl.java
Labels: feat

#47 test : SQL 추가 및 테스트 코드 추가
  src/main/java/com/kube/noon/feed/domain/Feed.java
  src/main/java/com/kube/noon/feed/domain/FeedAttachment.java
  src/main/java/com/kube/noon/feed/domain/FeedComment.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/resources/mybatis-mapper/feed/TagMapper.xml
  src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedCommentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
Labels: test

#45 feat : CustomerSupport 신고 구현
  src/main/java/com/kube/noon/building/dto/BuildingZzimDto.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/customersupport/domain/Report.java
  src/main/java/com/kube/noon/customersupport/dto/report/ReportDto.java
  src/main/java/com/kube/noon/customersupport/dto/report/ReportProcessingDto.java
  src/main/java/com/kube/noon/customersupport/enums/UnlockDuration.java
  src/main/java/com/kube/noon/customersupport/repository/CustomerSupportRepository.java
  src/main/java/com/kube/noon/customersupport/repository/ReportRepository.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
  src/test/java/com/kube/noon/building/service/TestBuildingService.java
  src/test/java/com/kube/noon/customersupport/Service/TestCustomerSupportService.java
  src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
Labels: feat

#39 feat: 환경설정 업데이트 및 조회 로직 구현
  src/main/java/com/kube/noon/building/service/buildingwiki/BuildingWikiRestTemplateServiceImpl.java
  src/main/java/com/kube/noon/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
  src/main/java/com/kube/noon/setting/domain/OperationInfo.java
  src/main/java/com/kube/noon/setting/domain/Setting.java
  src/main/java/com/kube/noon/setting/repository/OperationInfoRepository.java
  src/main/java/com/kube/noon/setting/repository/SettingRepository.java
  src/main/java/com/kube/noon/setting/service/SettingService.java
  src/main/java/com/kube/noon/setting/service/SettingServiceImpl.java
  src/test/java/com/kube/noon/building/service/TestBuildingWikiRestTemplateServiceImpl.java
  src/test/java/com/kube/noon/member/service/TestMemberService.java
  src/test/java/com/kube/noon/setting/service/TestSettingServiceImpl.java
Labels: feat

#48 feat: 알림 전송 및 저장 구현
  src/main/java/com/kube/noon/config/BeanConfig.java
  src/main/java/com/kube/noon/notification/domain/Notification.java
  src/main/java/com/kube/noon/notification/dto/NotificationDto.java
  src/main/java/com/kube/noon/notification/repository/NotificationRepository.java
  src/main/java/com/kube/noon/notification/service/NotificationService.java
  src/main/java/com/kube/noon/notification/service/NotificationServiceImpl.java
  src/main/java/com/kube/noon/notification/service/sender/CoolSmsNotificationAgent.java
  src/main/java/com/kube/noon/notification/service/sender/NotificationEmptyAgent.java
  src/main/java/com/kube/noon/notification/service/sender/NotificationTransmissionAgent.java
  src/test/java/com/kube/noon/notification/repository/TestNotificationRepository.java
  src/test/java/com/kube/noon/notification/service/TestNotificationServiceImpl.java
Labels: feat

#50 feat: 공통 모듈 - 검증 로직 분리/로깅
  src/main/java/com/kube/noon/common/logging/ConsoleColorCode.java
  src/main/java/com/kube/noon/common/logging/TraceLoggingAspect.java
  src/main/java/com/kube/noon/common/validator/IllegalServiceCallException.java
  src/main/java/com/kube/noon/common/validator/ValidationAspect.java
  src/main/java/com/kube/noon/common/validator/Validator.java
  src/main/java/com/kube/noon/config/BeanConfig.java
  src/test/java/com/kube/noon/common/validator/SampleService.java
  src/test/java/com/kube/noon/common/validator/SampleValidator.java
  src/test/java/com/kube/noon/common/validator/TestValidationAspect.java
Labels: feat

#51 feat : CustomerSupport 공지사항 구현 feat
  src/main/java/com/kube/noon/common/zzim/Zzim.java
  src/main/java/com/kube/noon/customersupport/dto/notice/NoticeDto.java
  src/main/java/com/kube/noon/customersupport/repository/NoticeRepository.java
  src/test/java/com/kube/noon/customersupport/repository/TestCustomerSupportRepository.java
Labels: feat

#53 feat : Winterhana/#32/feed sql : 피드와 관련된 JPA 코드 추가 및 테스트 완료
  src/main/java/com/kube/noon/common/zzim/Zzim.java
  src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedCommentRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagFeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
  src/main/resources/mybatis-mapper/feed/TagMapper.xml
  src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
Labels: feat, test

#55 feat: SettingRestController, PlacesRestController 구현
  src/main/java/com/kube/noon/common/messagesender/MessageSender.java
  src/main/java/com/kube/noon/common/messagesender/NotificationCoolSmsMessageSender.java
  src/main/java/com/kube/noon/common/messagesender/NotificationEmptyMessageSender.java
  src/main/java/com/kube/noon/common/messagesender/NotificationMessageSender.java
  src/main/java/com/kube/noon/config/BeanConfig.java
  src/main/java/com/kube/noon/notification/service/NotificationServiceImpl.java
  src/main/java/com/kube/noon/places/controller/PlacesRestController.java
  src/main/java/com/kube/noon/setting/controller/SettingRestController.java
  src/main/java/com/kube/noon/setting/domain/Setting.java
  src/main/java/com/kube/noon/setting/dto/SettingDto.java
  src/main/java/com/kube/noon/setting/service/SettingService.java
  src/main/java/com/kube/noon/setting/service/SettingServiceImpl.java
  src/test/java/com/kube/noon/setting/service/TestSettingServiceImpl.java
Labels: feat, refactor

#59 feat : Winterhana/#37/feed service : FeedService 추가, FeedSubService 추가 중
  src/main/java/com/kube/noon/feed/domain/Feed.java
  src/main/java/com/kube/noon/feed/domain/FeedAttachment.java
  src/main/java/com/kube/noon/feed/dto/FeedAttachmentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/FeedSubService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
Labels: feat, test

#57 feat : 빌딩 피드 AI 요약 구현
  src/main/java/com/kube/noon/building/repository/BuildingSummaryRepository.java
  src/main/java/com/kube/noon/building/repository/BuildingSummaryRepositoryImpl.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/common/ScheduledTasks.java
  src/test/java/com/kube/noon/building/service/TestBuildingService.java
  src/test/java/com/kube/noon/customersupport/repository/TestCustomerSupportRepository.java
Labels: feat

#61 feat: notification, setting 검증 로직 추가
  src/main/java/com/kube/noon/common/validator/IllegalServiceCallException.java
  src/main/java/com/kube/noon/common/validator/Problems.java
  src/main/java/com/kube/noon/common/validator/ValidationAspect.java
  src/main/java/com/kube/noon/notification/service/validator/NotificationServiceValidator.java
  src/main/java/com/kube/noon/setting/service/SettingServiceImpl.java
  src/main/java/com/kube/noon/setting/service/validator/SettingServiceValidator.java
  src/test/java/com/kube/noon/notification/service/validator/TestNotificationServiceValidator.java
  src/test/java/com/kube/noon/setting/service/validator/TestSettingServiceValidator.java
Labels: feat, refactor

#65 hotfix: ValidationAspect에서 발생하는 NullPointerException 해결
  src/main/java/com/kube/noon/common/validator/IllegalServiceCallException.java
  src/main/java/com/kube/noon/common/validator/Problems.java
  src/main/java/com/kube/noon/common/validator/ValidationAspect.java
  src/main/java/com/kube/noon/common/validator/Validator.java
  src/test/java/com/kube/noon/notification/service/TestNotificationServiceImpl.java
Labels: hotfix

#68 chore: Swagger를 통한 API 문서 작성 자동화
  pom.xml
  src/main/java/com/kube/noon/common/validator/IllegalServiceCallException.java
  src/main/java/com/kube/noon/config/WebConfig.java
  src/main/java/com/kube/noon/places/controller/PlacesRestController.java
  src/main/java/com/kube/noon/setting/controller/SettingRestController.java
Labels: chore

#70 feat : Winterhana/#37/feed service : FeedSubService 구현 완료, FeedStatisticsService 구현 완료
  src/main/java/com/kube/noon/feed/domain/FeedComment.java
  src/main/java/com/kube/noon/feed/dto/FeedBookmarkAndLikeDto.java
  src/main/java/com/kube/noon/feed/dto/FeedCntByTagDto.java
  src/main/java/com/kube/noon/feed/dto/FeedCommentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/FeedLIkeMemberDto.java
  src/main/java/com/kube/noon/feed/dto/FeedPopularityDto.java
  src/main/java/com/kube/noon/feed/dto/FeedViewCntByBuildingDto.java
  src/main/java/com/kube/noon/feed/dto/TagDto.java
  src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/FeedMyBatisRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/TagMyBatisRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/FeedStatisticsService.java
  src/main/java/com/kube/noon/feed/service/FeedSubService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedStatisticsServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
  src/main/resources/mybatis-mapper/feed/TagMapper.xml
  src/test/java/com/kube/noon/feed/repository/TestFeedAttachmentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedCommentRepository.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/repository/TestTagFeedRepository.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedStatisticsServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
Labels: feat, test

#73 feat : Green Eye 유해사진 필터링 구현 feat
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepository.java
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
  src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
Labels: feat

#79 feat: Chatbot 구현
  src/main/java/com/kube/noon/customersupport/service/ChatbotService.java
  src/main/java/com/kube/noon/customersupport/service/ChatbotServiceImpl.java
  src/test/java/com/kube/noon/customersupport/service/TestChatbotServiceImpl.java
Labels: feat

#81 feat : 페이징 적용 및 Service Test
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepository.java
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
  src/main/java/com/kube/noon/customersupport/repository/NoticeRepository.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
  src/main/resources/mybatis-mapper/buildingProfile/BuildingProfileMapper.xml
  src/test/java/com/kube/noon/customersupport/repository/TestCustomerSupportRepository.java
  src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
Labels: feat, test

#85 feat : Building Controller 구현
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/repository/BuildingSummaryRepositoryImpl.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
Labels: feat

#84 feat : 피드 추천 알고리즘 구현 완료, FeedController 구현 완료 및 테스트 대기
  pom.xml
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/MemberLikeTagDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/FeedMyBatisRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/FeedStatisticsService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedStatisticsServiceImpl.java
  src/main/java/com/kube/noon/feed/service/recommend/FeedRecommendationMemberId.java
  src/main/java/com/kube/noon/feed/service/recommend/MinMaxScaler.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedStatisticsServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
Labels: feat

#88 hotfix : getFeedListByBuilding Error 해결
  .gitignore
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/recommend/FeedRecommendationMemberId.java
Labels: hotfix

#89 fix : FeedService 관련 버그 해결
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/domain/Feed.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/dto/TagFeedDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: fix

#91 feat : customer support controller
  src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
  src/main/java/com/kube/noon/customersupport/dto/report/ReportProcessingDto.java
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportService.java
  src/main/java/com/kube/noon/customersupport/service/CustomerSupportServiceImpl.java
  src/main/java/com/kube/noon/feed/repository/FeedAttachmentRepository.java
  src/test/java/com/kube/noon/customersupport/service/TestCustomerSupportService.java
Labels: feat

#93 feat, docs : FeedController 테스트 완료, 목록 페이징 작업, Swagger 명세화
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/AddTagDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/TagRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: feat, test

#101 refactor : 피드 내부 로직 관련 수정 사항
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/dto/UpdateFeedDto.java
  src/main/java/com/kube/noon/feed/repository/TagFeedRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: feat, fix

#104 feat: KakaoTokenSupport 나머지 구현
  src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
  src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
Labels: feat

#108 chore: 빌드 세팅
  .gitignore
  Dockerfile
  pom.xml
  src/main/resources/application.properties
Labels: chore

#110 chore: CORS 설정
  src/main/java/com/kube/noon/config/WebConfig.java
  src/main/resources/application.properties
Labels: chore

#118 hotfix: Spring Security 접근 권한 문제
  src/main/java/com/kube/noon/config/WebSecurityConfig.java
Labels: fix

#120 chore: WAR -> JAR
  Dockerfile
  pom.xml
Labels: chore

#122 fix: UpdateMemberDto에서 Nickname이 null일 때 검증하지 않음
  src/main/java/com/kube/noon/member/validator/MemberValidationRule.java
Labels: fix

#126 feat: 위도, 경도 좌표로 건물 정보 받아오기 구현
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/repository/BuildingProfileRepository.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/common/security/support/KakaoTokenSupport.java
  src/main/java/com/kube/noon/places/domain/PositionRange.java
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
  src/main/java/com/kube/noon/places/service/PlacesService.java
  src/main/java/com/kube/noon/places/service/PlacesServiceImpl.java
  src/test/java/com/kube/noon/building/repository/TestBuildingProfileRepository.java
  src/test/java/com/kube/noon/building/service/TestBuildingService.java
Labels: feat

#127 refactor : View와 연관된 비즈니스 로직 수정
  src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: refactor

#129 fix : 피드 목록에 대한 내부 로직 수정
  src/main/java/com/kube/noon/feed/dto/FeedPopularityDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: fix

#135 HOTFIX: Cookie에 도메인 설정
  src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
  src/main/java/com/kube/noon/config/WebSecurityConfig.java
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
  src/main/resources/application.properties
Labels: hotfix

#132 refactor: 채팅방 검색 리팩토링
  src/main/java/com/kube/noon/chat/controller/ChatroomRestController.java
  src/main/java/com/kube/noon/chat/domain/ChatEntrance.java
  src/main/java/com/kube/noon/chat/domain/Chatroom.java
  src/main/java/com/kube/noon/chat/dto/ChatroomSearchResponseDto.java
  src/main/java/com/kube/noon/chat/repository/ChatroomRepository.java
  src/main/java/com/kube/noon/chat/service/ChatroomSearchService.java
  src/main/java/com/kube/noon/chat/serviceImpl/ChatroomSearchServiceImpl.java
  src/test/java/com/kube/noon/chat/ChatroomSearchServiceImplTest.java
  src/test/java/com/kube/noon/chat/repository/TestChatroomRepository.java
Labels: refactor

#143 refactor: BuildingSearchResponseDto에 누락된 데이터 추가
  src/main/java/com/kube/noon/building/dto/BuildingSearchResponseDto.java
Labels: refactor

#149 fix: 검색 관련 에러 제거
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
Labels: fix

#152 refactor: 좌표를 파라미터로 건물 프로필 받아올 때 응답 케이스 추가
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/dto/BuildingNotFoundResponseDto.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
Labels: refactor

#155 chore: CORS 설정에서 exposedHeader 설정
  src/main/java/com/kube/noon/config/WebConfig.java
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
Labels: chore

#157 chore: 쿠키 설정
  src/main/java/com/kube/noon/config/WebConfig.java
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
Labels: chore

#162 refactor : 피드 관련 데이터 수정
  src/main/java/com/kube/noon/feed/dto/FeedPopularityDto.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
Labels: refactor

#164 feat: JWT access token으로 현재 로그인 유저 정보 가져오기
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
Labels: feat

#165 feat: BuildingWikiRestController 구현
  src/main/java/com/kube/noon/building/controller/BuildingWikiRestController.java
  src/main/java/com/kube/noon/building/dto/wiki/BuildingWikiEditRequestDto.java
  src/main/java/com/kube/noon/building/dto/wiki/BuildingWikiPageResponseDto.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/building/service/BuildingWikiService.java
  src/main/java/com/kube/noon/building/service/buildingwiki/BuildingWikiEmptyServiceImpl.java
  src/main/java/com/kube/noon/building/service/buildingwiki/BuildingWikiRestTemplateServiceImpl.java
  src/test/java/com/kube/noon/building/service/TestBuildingWikiRestTemplateServiceImpl.java
  src/test/java/com/kube/noon/building/service/buildingwiki/TestBootBuildingWikiRestTemplateServiceImpl.java
Labels: feat

#166 refactor: 건물 위키 REST API 명세 변경
  src/main/java/com/kube/noon/building/controller/BuildingWikiRestController.java
  src/test/java/com/kube/noon/building/service/buildingwiki/TestBootBuildingWikiRestTemplateServiceImpl.java
Labels: refactor

#168 refactor: 네이버 지역 검색 API 사용
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
  src/main/java/com/kube/noon/places/repository/PlacesSearchApiNaverMapsApiRepository.java
Labels: refactor

#173 refactor : 사진 / 동영상 사진을 가져오기 위한 데이터 수정
  src/main/java/com/kube/noon/common/ObjectStorageAPI.java
  src/main/java/com/kube/noon/feed/dto/FeedAttachmentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
Labels: refactor

#177 fix: 리프레시 토큰 필터 관련 문제 해결
  src/main/java/com/kube/noon/common/security/filter/TokenRefreshFilter.java
Labels: fix

#184 feat : 투표 게시판 구현을 위한 로직 추가
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/domain/FeedVotes.java
  src/main/java/com/kube/noon/feed/domain/converter/ListToIntegerConverter.java
  src/main/java/com/kube/noon/feed/domain/converter/ListToStringConverter.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
  src/main/java/com/kube/noon/feed/repository/FeedVotesRepository.java
  src/main/java/com/kube/noon/feed/service/FeedVotesService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
Labels: feat

#185 remove: PlaceSearchApiNaverMapsApiRepository 삭제
  src/main/java/com/kube/noon/places/repository/PlacesSearchApiNaverMapsApiRepository.java
Labels: remove

#187 fix : 투표 관련 작업 중 요구사항 변경 및 기타 버그 해결
  src/main/java/com/kube/noon/common/zzim/ZzimRepository.java
  src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: fix

#188 feat : 프로필 사진 버킷 생성 및 분리
  src/main/java/com/kube/noon/common/ObjectStorageAPIProfile.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
Labels: feat

#189 feat: 리소스 접근 제어 필터 구현
  src/main/java/com/kube/noon/common/security/accesscontrol/AccessControl.java
  src/main/java/com/kube/noon/common/security/accesscontrol/AccessControlTrigger.java
  src/main/java/com/kube/noon/common/security/accesscontrol/util/RequestPathNode.java
  src/main/java/com/kube/noon/common/security/accesscontrol/util/RequestPathTree.java
  src/main/java/com/kube/noon/common/security/filter/AccessControlFilter.java
  src/main/java/com/kube/noon/config/WebSecurityConfig.java
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
  src/main/java/com/kube/noon/setting/accesscontrol/SettingAccessControl.java
  src/test/java/com/kube/noon/common/security/accesscontrol/util/TestRequestPathTree.java
  src/test/java/com/kube/noon/common/security/support/TestJwtSupport.java
Labels: feat

#191 chore: add profile - accesscontrol
  Dockerfile
  src/main/java/com/kube/noon/config/WebSecurityConfig.java
Labels: chore

#193 feat : building chart
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/dto/BuildingChartDto.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/customersupport/repository/AttachmentFilteringRepositoryImpl.java
Labels: feat

#194 feat : 간단한 투표 로직 완성
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/domain/FeedVotes.java
  src/main/java/com/kube/noon/feed/domain/converter/MapToJsonConverter.java
  src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
  src/main/java/com/kube/noon/feed/service/FeedVotesService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
Labels: feat

#197 feat : 투표 관련 로직 수정, 확성기 관련 로직 추가
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/FeedMegaphoneDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
Labels: feat

#198 refactor : 차트 정렬 기준 변경에 따른 코드 수정
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
Labels: refactor

#201 fix: 건물명으로 건물명 대신 도로명주소가 뜨던 거 수정
  src/main/java/com/kube/noon/places/repository/PlacesNaverMapsApiRepositoryImpl.java
Labels: fix

#206 feat: 구글 로그인 인증/인가 로직 구현
  src/main/java/com/kube/noon/common/security/authentication/authtoken/GoogleTokenAuthentication.java
  src/main/java/com/kube/noon/common/security/authentication/authtoken/generator/GoogleTokenAuthenticationGenerator.java
  src/main/java/com/kube/noon/common/security/authentication/provider/GoogleTokenAuthenticationProvider.java
  src/main/java/com/kube/noon/common/security/support/GoogleTokenSupport.java
  src/main/java/com/kube/noon/config/WebSecurityConfig.java
  src/main/java/com/kube/noon/member/controller/MemberRestController.java
  src/main/java/com/kube/noon/member/dto/auth/GoogleLoginRequestDto.java
Labels: feat

#207 feat : 댓글 관련 수정 사항 추가, 이벤트 피드에 대한 테이블 추가 및 이에 대한 로직 추가
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/domain/FeedEvent.java
  src/main/java/com/kube/noon/feed/dto/FeedCommentDto.java
  src/main/java/com/kube/noon/feed/dto/FeedDto.java
  src/main/java/com/kube/noon/feed/dto/FeedEventDto.java
  src/main/java/com/kube/noon/feed/dto/FeedVotesDto.java
  src/main/java/com/kube/noon/feed/dto/UpdateFeedDto.java
  src/main/java/com/kube/noon/feed/repository/FeedEventRepository.java
  src/main/java/com/kube/noon/feed/service/FeedSubService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedVotesServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
  src/test/java/com/kube/noon/feed/service/TestFeedSubServiceImpl.java
Labels: feat

#208 fix : 건물 등록신청 로직 수정
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/customersupport/controller/CustomerSupportRestController.java
Labels: fix

#212 fix : 좋아요, 북마크, 목록 보기에 대한 로직 재구성
  src/main/java/com/kube/noon/common/zzim/Zzim.java
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/impl/FeedSubServiceImpl.java
Labels: fix

#216 fix : null 처리 및 Object Storage 설정 변경
  src/main/java/com/kube/noon/common/ObjectStorageAPI.java
  src/main/java/com/kube/noon/common/ObjectStorageAPIProfile.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
Labels: fix
