Repository kuberMAPtes/noon-main-api-server, pull requests merged in 2024-07, with the labels that each got.

#224 feat, fix : 이벤트 피드 구현 및 버그 수정
  src/main/java/com/kube/noon/feed/controller/FeedRestController.java
  src/main/java/com/kube/noon/feed/dto/FeedEventDto.java
  src/main/java/com/kube/noon/feed/dto/FeedLIkeMemberDto.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/repository/FeedEventRepository.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/repository/mybatis/FeedMyBatisRepository.java
  src/main/java/com/kube/noon/feed/service/FeedService.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
  src/test/java/com/kube/noon/feed/service/TestFeedServiceImpl.java
Labels: feat, fix

#229 fix: chatbot 안 되는 버그 수정
  src/main/java/com/kube/noon/customersupport/service/ChatbotServiceImpl.java
Labels: fix

#230 fix : 필요한 데이터 추가
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/repository/FeedCommentRepository.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
Labels: fix

#238 feat : 자신이 작성한 피드, 건물 프로필 피드 최신순으로 정렬
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/test/java/com/kube/noon/feed/repository/TestFeedRepository.java
Labels: fix

#236 refactor : Check Subscriber List PublicRange
  src/main/java/com/kube/noon/building/controller/BuildingProfileRestController.java
  src/main/java/com/kube/noon/building/dto/SubscriberDto.java
  src/main/java/com/kube/noon/building/service/BuildingProfileService.java
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
  src/main/java/com/kube/noon/member/service/impl/MemberServiceImpl.java
Labels: refactor

#235 refactor: 코드를 리팩토링했습니다.
  src/main/java/com/kube/noon/common/validator/Problems.java
  src/main/java/com/kube/noon/setting/service/validator/SettingServiceValidator.java
  src/test/java/com/kube/noon/setting/service/validator/TestSettingServiceValidator.java
Labels: refactor

#232 feat: 알림 수신 여부 확인
  src/main/java/com/kube/noon/notification/service/NotificationServiceImpl.java
Labels: feat, refactor

#241 feat : 필요한 기능 추가, 정렬 개선
  src/main/java/com/kube/noon/feed/domain/Feed.java
  src/main/java/com/kube/noon/feed/dto/FeedSummaryDto.java
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/java/com/kube/noon/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/kube/noon/feed/service/recommend/FeedRecommendationMemberId.java
Labels: feat

#240 chore: 채팅방 활발함 기준 인하
  src/main/java/com/kube/noon/building/service/BuildingProfileServiceImpl.java
Labels: chore

#242 fix : 피드 정렬 및 삭제 관련 버그 수정
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
Labels: fix

#243 fix : 인기 태그와 건물 구독 별 피드 목록 정렬 수정
  src/main/java/com/kube/noon/feed/repository/FeedRepository.java
  src/main/resources/mybatis-mapper/feed/FeedMapper.xml
Labels: fix
